version: '3.4'

x-logging: &logging
  driver: json-file
  options:
    max-size: 100m
    max-file: '5'

services:
  bot:
    image: registry.gitlab.com/pawabot/pawa:${VERSION}
    depends_on:
      - datastore
    env_file:
      - ${ENV:-sample}.env
    environment:
      - TZ=America/Los_Angeles
      - JAVA_TOOL_OPTIONS=-Xmx1G
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/app/data/oom.bin
    volumes:
      - data:/app/data
      - ./logs:/app/logs
    restart: on-failure:100
    logging:
      <<: *logging
  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    logging:
      <<: *logging
  #  data:
  #    image: metabase/metabase:v0.34.1
  #    environment:
  #      - JAVA_TOOL_OPTIONS=-Xmx300m
  #      - TZ=America/Los_Angeles
  #      - MB_DB_FILE=/opt/data/metabase
  #    ports:
  #      - 3000:3000
  #    volumes:
  #      - data:/opt/data
  #    logging:
  #      <<: *logging
  datastore:
    image: minio/minio:RELEASE.2020-04-10T03-34-42Z
    command: -c "MINIO_SECRET_KEY=$$DS_SECRET_KEY MINIO_ACCESS_KEY=$$DS_ACCESS_KEY minio gateway b2"
    entrypoint: sh
    env_file:
      - ${ENV:-sample}.env
    environment:
      - TZ=America/Los_Angeles
    logging:
      <<: *logging
  nginx:
    image: nginx:1.17-alpine
    command: /bin/sh -c "envsubst '$${BOT_HOST},$${DATA_HOST},$${DATA_WHITELIST_IP}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
    environment:
      - BOT_HOST=${BOT_HOST:-localhost}
      - DATA_HOST=${DATA_HOST:-localhost}
      - DATA_WHITELIST_IP=${DATA_WHITELIST_IP:-127.0.0.1}
    volumes:
      - ${CONF:-./}nginx.conf:/etc/nginx/nginx.conf.template
    ports:
      - 80:80
    depends_on:
      - bot
      #      - data
      - portainer
    logging:
      <<: *logging

volumes:
  portainer_data:
  data:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/pawa/data
